### ISSUE TITLE
Fix AppVeyor CI

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx-metis#41]
This is a requirement for declaring Windows support.

**Comment by OrkoHunter** [comment]
Rewriting the tests #26 would do it.

**Comment by OrkoHunter** [comment]
There are two failures over the Appveyor CI in [the latest build](https://ci.appveyor.com/project/chebee7i/networkx-metis-1lf0f/build/1.0.37) only because of the x64 architecture. There seems to be a bug probably unresolved for compiling `msvc9compiler.py` over x64 windows machines. It has temporary fixes like changing `vcvarsall.bat` file somehow.

**Comment by OrkoHunter** [comment]
I think it can be tricky to do the fix over Appveyor. Maybe we do not test for x64 ?
